### PR TITLE
Fix HKUST recipe

### LINKED ISSUE #2321: [Dependency] mmseg on egs/hkust/asr1
## Summary

In run.sh stage 0: Data preparation

script requires mmseg on [hkust_segment.py](https://github.com/42qu/mmseg)
however, mmseg using pyhon 2.7
and in [hkust_data_prep.sh](https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/local/hkust_data_prep.sh)
```
#transcripts normalization and segmentation
#(this needs external tools),
python3 -c "import mmseg" 2>/dev/null || \
  (echo "mmseg is not found. Checkout tools/extra/install_mmseg.sh" && exit 1;)

cat $train_dir/transcripts.txt |\
  sed -e 's/<foreign language=\"[a-zA-Z]\+\">/ /g' |\
  sed -e 's/<\/foreign>/ /g' |\
  sed -e 's/<noise>\(.\+\)<\/noise>/\1/g' |\
  sed -e 's/((\([^)]\{0,\}\)))/\1/g' |\
  local/hkust_normalize.pl |\
  python3 local/hkust_segment.py |\
  awk '{if (NF > 1) print $0;}' > $train_dir/text || exit 1;

cat $dev_dir/transcripts.txt |\
  sed -e 's/<foreign language=\"[a-zA-Z]\+\">/ /g' |\
  sed -e 's/<\/foreign>/ /g' |\
  sed -e 's/<noise>\(.\+\)<\/noise>/\1/g' |\
  sed -e 's/((\([^)]\{0,\}\)))/\1/g' |\
  local/hkust_normalize.pl |\
  python3 local/hkust_segment.py |\
  awk '{if (NF > 1) print $0;}' > $dev_dir/text || exit 1;
```
seems use python3 to execute python2 script

I also tried [py3mmseg](https://github.com/bxshi/py3mmseg)
unfortunately, it didn't work.

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
Fix #2321#2433

- I forked py3mmseg for python3.7: https://github.com/kamo-naoyuki/py3mmseg
- Add -L option to find. This recipe is failed if the specified corpus directory is a symlink. We should use find command more carefully.
- Now speed perturbation is applied after feature extraction. It causes the problem of #2433. We should use utils/fix_data_dir.sh more carefully. 
  - Such a ridiculous problem never happens in espnet2. We should move all to espnet2 quickly.

### CODE REVIEW

File: ci/install.sh [hunk 1]
```diff
@@ -19,7 +19,7 @@ ${CXX:-g++} -v
     fi
     make TH_VERSION="${TH_VERSION}"
 
-    make nkf.done moses.done mwerSegmenter.done pesq pyopenjtalk.done
+    make nkf.done moses.done mwerSegmenter.done pesq pyopenjtalk.done py3mmseg.done
```
Comment (ShigekiKarita) [inline ci/install.sh:22]: Why you need this in CI?

Comment (kamo-naoyuki) [reply ci/install.sh:22]: These targets are installed to test the installation script. I'd like to test Makefile because sometimes it was broken due to my modification.
(Sometimes, pesq installation is failed due to the source server, so I'm thinking to delete pesq)

Comment (ShigekiKarita) [reply ci/install.sh:22]: ideally it should be in a different script like .github/workflows/make.yml
```yml
on:
  push:
    paths:
    - tools/Makefile

jobs:
  extra:
    steps:
    - run: make extra
```
to reduce the testing time

Comment (kamo-naoyuki) [reply ci/install.sh:22]: Hmm, ideally, yes. More ideally, we should split integration test and unittest, and linter test  independently.
Okay, I keep it in mind, but not in this PR.

Comment (ShigekiKarita) [reply ci/install.sh:22]: OK. I'm not sure if codecov supports independent coverage xml files from different jobs.

Comment (ShigekiKarita) [reply ci/install.sh:22]: I think linter before testing is good early stopping. Anyway, the independent linter script is nice for local env.

Comment (kamo-naoyuki) [reply ci/install.sh:22]: I see, it sounds hard, so we should keep integration tests and unit tests in one CI for now.

**Comment by kan-bayashi** [comment]
Let us merge this PR.
