### PR TITLE
Chainer fix mixed input

### LINKED ISSUE #1091: chainer is not working with `--ngpu 0`
In my environment `master`, `egs/mini_an4/run.sh --ngpu 0 --backend chainer` is not working now. I attached train.log
[train.log](https://github.com/espnet/espnet/files/3504860/train.log)

### PR DESCRIPTION
**Pull request by Fhrozen**
To resolve #1091.

The problem is that for the first iteration, the custom updater return an `CpuDevice`, so when it is compared inside the `CustomConverter` the comparison return cuda.cupy. For some reason, in the first iter the CustomUpdater uses the super `CpuDevice` and then is set to an int `-1`, so it is not possible to use the xp from the  `CpuDevice`. Currently i applied the fix for both (rnn and transf) but transformer always uses np array in the CustomConverter so it does not show this problem.

### CODE REVIEW

**Comment by Fhrozen** [comment]
@sw005320 , btw I do not think that is possible to implement a test given that the error is generated for the CustomUpdater.

**Comment by kan-bayashi** [comment]
Just add `run.sh --stage 3 --backend chainer` just after `run.sh` to check it.
https://github.com/espnet/espnet/blob/6759e7fcb8386b845a8a48ef779db3977f599a05/ci/test_integration.sh#L3-L7

**Comment by sw005320** [comment]
Please check our new integration test https://github.com/espnet/espnet/blob/master/ci/test_integration.sh
This actually executes `run.sh`, and you can make sure our recipe is working without errors or not.

**Comment by Fhrozen** [comment]
@sw005320. I just added the test.
I apologize for the inconveniences. Sometimes, I forgot about that new test. I  was just thinking about pytest.

**Comment by sw005320** [comment]
No problem, but it seems that it is failed at https://travis-ci.org/espnet/espnet/jobs/572343376#L3162
I don't know why the CI was passed even it's failed. 
@kan-bayashi, @ShigekiKarita, do you have any ideas?

File: ci/test_integration.sh [hunk 1]
```diff
@@ -4,6 +4,7 @@
 (
     cd ./egs/mini_an4/asr1 || exit 1
     ./run.sh
+    ./run.sh --stage 3 --backend chainer
```
Comment (ShigekiKarita) [inline ci/test_integration.sh]: Add `set -euo pipefail` to the head of this filE. I forgot it.

**Comment by ShigekiKarita** [comment]
https://5539-114054873-gh.circle-artifacts.com/0/home/circleci/repo/egs/mini_an4/asr1/exp/train_nodev_chainer_train/train.log

Circle CI saves train.log in artifact tab. It seems to still require cupy. Try uninstalling it when you fix that.

File: espnet/nets/chainer_backend/rnn/training.py [hunk 2]
```diff
@@ -17,10 +17,14 @@
...
-from cupy.cuda import nccl
-
 import numpy as np
 
+try:
+    # Calls nccl when cupy is installed for CustomParallelUpdater (only for gpu support)
+    from cupy.cuda import nccl
+except Exception:
+    pass
+
```
Comment (kan-bayashi) [inline espnet/nets/chainer_backend/rnn/training.py]: Why don't you move above part to `CustomParallelUpdater.__init__()`?

File: espnet/nets/chainer_backend/transformer/training.py [hunk 3]
```diff
@@ -19,10 +19,14 @@
...
 
 from chainer.training import extension
-from cupy.cuda import nccl
 
 import numpy as np
 
+try:
+    from cupy.cuda import nccl
+except Exception:
+    pass
```
Comment (kan-bayashi) [inline espnet/nets/chainer_backend/transformer/training.py]: ditto

File: espnet/nets/chainer_backend/rnn/training.py (hunk 2 above)
Comment (kan-bayashi) [reply espnet/nets/chainer_backend/rnn/training.py]: Just call `from cupy.cuda import nccl` in `CustomParallelUpdater.__init__()`.

File: ci/test_integration.sh [hunk 4]
```diff
@@ -1,9 +1,20 @@
...
 
+set -euo pipefail
+
+if [ -z ${LD_LIBRARY_PATH+x} ]; then
+    LD_LIBRARY_PATH=$(pwd)/chainer_ctc/ext/warp-ctc/build
+else
+    LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/chainer_ctc/ext/warp-ctc/build
+fi
+
+export LD_LIBRARY_PATH
```
Comment (kan-bayashi) [inline ci/test_integration.sh]: It is better to add some comments here. (`path.sh`)
And you can use `shellcheck disable=SC...` to simplify

```bash
# NOTE: LD_LIBRARY_PATH is updated in `path.sh` but does not work. (Maybe?)
# shellcheck disable=SC<shell_check_code_number>
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/chainer_ctc/ext/warp-ctc/build

```

Comment (Fhrozen) [reply ci/test_integration.sh]: The problem about D_LIBRARY_PATH is that it adds the chainer_ctc in tools (by default in pc env) but in ci it is install only in `pwd` (no tools) that is why raises error in Ubuntu tests.

I will disable SC for LD_LIBRARY_PATH

Comment (kan-bayashi) [reply ci/test_integration.sh]: I see.
Another choice is as follows:
https://github.com/espnet/espnet/blob/6759e7fcb8386b845a8a48ef779db3977f599a05/ci/test_python.sh#L13

Comment (ShigekiKarita) [reply ci/test_integration.sh]: I think fixing `install.sh` to put `chainer_ctc` in `tools/` is better because it is closer to our usage.

File: espnet/nets/chainer_backend/rnn/training.py (hunk 2 above)
Comment (ShigekiKarita) [reply espnet/nets/chainer_backend/rnn/training.py]: I agree. Because nccl is only used for multi GPU training, it should be also optional for single GPU training.

File: espnet/nets/chainer_backend/rnn/training.py [hunk 5]
```diff
@@ -73,6 +77,8 @@ def __init__(self, train_iter, optimizer, converter, device, accum_grad=1):
         self.forward_count = 0
         self.accum_grad = accum_grad
         self.start = True
+        # To solve #1091, it is required to set the variable inside this class.
+        self.device = device
```
Comment (ShigekiKarita) [inline espnet/nets/chainer_backend/rnn/training.py]: I do not think you need this because base class does
https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainer/training/updaters/standard_updater.py#L92

File: espnet/nets/chainer_backend/transformer/training.py [hunk 6]
```diff
@@ -75,6 +79,7 @@ def __init__(self, train_iter, optimizer, converter, device, accum_grad=1):
         self.accum_grad = accum_grad
         self.forward_count = 0
         self.start = True
+        self.device = device
```
Comment (ShigekiKarita) [inline espnet/nets/chainer_backend/transformer/training.py]: ditto

File: espnet/nets/chainer_backend/rnn/training.py (hunk 5 above)
Comment (kan-bayashi) [reply espnet/nets/chainer_backend/rnn/training.py]: Problem maybe be caused from this line.
https://github.com/espnet/espnet/blob/63b9cb451ab17e17506347f29cd0837d978647a8/espnet/nets/chainer_backend/rnn/training.py#L234
In base class, `self.device` is converted to `CpuDevice`.

https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainer/training/updaters/standard_updater.py#L71

Therefore, we should change if-condition like:
```python
xp = cuda.cupy if not isinstance(device, chainer.backends.CpuDevice) else np 
```

Comment (Fhrozen) [reply espnet/nets/chainer_backend/rnn/training.py]: The interesting part is that device is `chainer.backends.CpuDevice` in the first iter only, after that it becomes a int (-1 or the gpuid). I was also expecting to be a `CpuDevice` the whole training so it will be possible to extract the xp from the self device (So the if is no longer requires) but sadly it was not as expected. This is the only solution which I found without adding more lines. If you tried any other besides the mentioned let me know, but I could not find it.. T.T

Comment (kan-bayashi) [reply espnet/nets/chainer_backend/rnn/training.py]: Now I understood your point.
I doubt that following part:
https://github.com/espnet/espnet/blob/63b9cb451ab17e17506347f29cd0837d978647a8/espnet/asr/chainer_backend/asr.py#L286-L289
https://github.com/espnet/espnet/blob/63b9cb451ab17e17506347f29cd0837d978647a8/espnet/asr/asr_utils.py#L80
But easiest solution seems yours. 
Why don't your add `TODO(...):` comment in this time?
@ShigekiKarita how do you think?

**Comment by ShigekiKarita** [comment]
Thank!
